image: docker:latest

stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  FRAPPE_VERSION: v13.37.0
  ERPNEXT_VERSION: v13.36.3

build_tags:
  stage: build
  only:
    refs:
      - version-13
    changes:
      - excel_erpnext/__init__.py
  before_script:
    # Install os dependencies
    - apk --update add openssh-client git jq curl
    # Login to container registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    # Install buildx
    - mkdir -p $HOME/.docker/cli-plugins
    - curl -sSLo $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --name ci_build_v13_tag --use
  script:
    - export VERSION=$(cat excel_erpnext/__init__.py | grep version | sed "s|__version__ = ||g" | sed "s|'||g")
    - docker buildx bake --push
    # Cleanup runner
    - docker buildx stop ci_build_v13_tag
    - docker buildx rm ci_build_v13_tag
    - docker volume prune -f

build_latest:
  stage: build
  only:
    - version-13
  before_script:
    # Install os dependencies
    - apk --update add openssh-client git jq curl
    # Login to container registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    # Install buildx
    - mkdir -p $HOME/.docker/cli-plugins
    - curl -sSLo $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --name ci_build_v13_latest --use
  script:
    - export VERSION=version-13
    - docker buildx bake --push
    # Cleanup runner
    - docker buildx stop ci_build_v13_latest
    - docker buildx rm ci_build_v13_latest
    - docker volume prune -f
